[project]
name = "soccerway"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.4",
    "selenium>=4.35.0",
    "webdriver-manager>=4.0.2",
    "pandas>=2.0.0",
    "openpyxl>=3.1.0",
]
